### ISSUE TITLE
Time Zone conversion

### ISSUE THREAD

**Issue by Tsvetoslav88** [vexelon-dot-net/currencybg.server#35]
Сега като правя имплементация за изчитане изчитане на валутите от сървъра забелязах следното поведение. Подавам дата в българска часова зона - 2016-08-31T20:55:06**+03:00** и сървъра ми връща датата в друга часова зона 2016-08-31T14:00**-0400** Пр. http://currencybg-tsvetoslav.rhcloud.com/currencybg.server/api/currencies/today/2016-08-31T20:55:06+03:00
Направих същия тест, но към локалания ми сървъра и този проблем го няма: http://localhost:8080/currencybg.server/api/currencies/today/2016-07-16T20:55:06+0300/300 -> "date": "2016-07-16T21:00+0300",
До колкото си спомням, часовата зона на сървъра ще ни бъде винаги БГ?

**Comment by Tsvetoslav88** [comment]
Между временно, аз погледна сега какво се връща в приложението и там изглежда всичко да е наред. Подавам следния час - 2016-08-31T20:55:06+02:00, и от сървъра ми връща с един час разлика.
![datetime](https://cloud.githubusercontent.com/assets/8929789/18256115/b78828b4-73b9-11e6-969e-0bdd88d1cabd.jpg)
Може би проблема е в HttpRequester, който ползвам за Mozilla. Ако искаш само тествай с горния линк, не му отделяй за сега много време :)

**Comment by petarov** [comment]
Да, май има пропуск от моя страна. Подаденото време ще се преобразува на Server Timezone-та и така ще се сравни в базата. Но в базата всъщност датите ги записваме както са от източниците, без time zone-a, т.е., зоната винаги е _Europe/Sofia_. Ще го погледна пак по-късно да потвърдя.

**Comment by Tsvetoslav88** [comment]
Може ли да се затвори този тикет след Merge на бранч "bugfix/#35-api-db-datetime" към master?

**Comment by petarov** [comment]
Мисля, че да. Направи един request към test server-a, трябва да връща
коректни дати сега, и може да го затворим това issue.


2016-09-07 9:23 GMT+02:00 Tsvetoslav88 <notifications@github.com>:

**Comment by Tsvetoslav88** [comment]
Проблемът е оправен в бранч #36
