### ISSUE TITLE
Проверка и евнт. оптимизация на API данните

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#4]
При теглене на валути от източник данните могат да надхвърлят 100К. Трябва да се провери и да се намери оптимално решение.

**Comment by Tsvetoslav88** [comment]
Създаване на нови 2 метода в API(getAllRatesForDate(...)), които по подаден DateTime взимат валутите, за текущия ден, след подадения час.

**Comment by petarov** [comment]
За формата на подадния DateTime към Url на  API-то. Предлагам да е само час и мин., с др. думи, формат `HH:mm`.

**Comment by petarov** [comment]
Като инфо, за момента с 6 мин. интервал валутите събрани за 1 цял връщат 800kb json.

**Comment by petarov** [comment]
Текщите интервали са:

- Тавекс - на 30 мин.
- Полана1 - на 7 часа
- ФИБ - на 2 часа

Тестовите данни се събират в момента, след което ще видя за 1 пълен ден колко е обема на информацията през API-то.

**Comment by petarov** [comment]
За момента данните за 1 ден са около 200kb.
