### ISSUE TITLE
Нов източник: www.factorin.bg

### ISSUE THREAD

**Issue by Hristov-Metodi** [vexelon-dot-net/currencybg.server#44]
Добавяне на http://www.factorin.bg/bg/ към списъка с източници

**Comment by Tsvetoslav88** [comment]
Factorin е добавено при мен локално. Трябва да се видим следните неща:
- време на обновяване - ?
- сутрин(през седмицата) от колко да се стартира обновяването - ?
- вечер(през седмицата) до колко да се стартира обновяването - ?
- сутрин(уикенда) от колко да се стартира обновяването - ?
- вечер(уикенда) до колко да се стартира обновяването - ?
- неделя дали да се стартира - ?
, за да преглася DDL за базата и да го качим на сървъра да събираме данни.

Това което забелязах е, че днес последното обновяване е било в  - 14.12.2016 17:26.
В неделя мисля, че не качват данни за валути.
Остава да проверим и другите неща.

**Comment by petarov** [comment]
Цецо,аз предлагам същите настройки като при Тавекс като за начало. На тоя етап би било достатъчно.

**Comment by Tsvetoslav88** [comment]
Добре, Пепи. Прикачан в тикета и insert скрипта, когато решим, може да качим кода и да изпълним скрипта.
