### ISSUE TITLE
E-mail репорти/известия

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#48]
Направихме интеграция с Telegram - ref #11, но в крайна сметка може би ще е добре да си имаме чиста E-mail интеграция. Можем да я реализираме посредством API-то на [SparkPost](https://www.sparkpost.com/). Ползвал съм го преди и е надеждно.

Това, което трябва да се направи е:

1. - [ ] Нов `Reporter` class, който имплементира [java-sparkpost](https://github.com/sparkpost/java-sparkpost) библиотеката и праща репортите. 
2. - [ ] Параметър в config файла, в/от който да пипаме SparkPost API key-a.
3. - [ ] Параметър в config файла, който да съдържа CSV списък с e-mail адреси, на които да се пращат репортите.

**Comment by Tsvetoslav88** [comment]
Аз гледам, че за него ще ни трябва domain, имаме ли такъв?

**Comment by petarov** [comment]
Домейн има налице, да - vexelon.net

**Comment by Tsvetoslav88** [comment]
А имаме ли регистрация в app.sparkpost.com, защото до колкото виждам трябва имаме регистрация с Домейн, след което трябва да се вземем API_KEY и да направим тест дали работи. Между другото в гит гледам, че е даден Maven dependency, а ние ползваме grade - https://github.com/sparkpost/java-sparkpost

**Comment by petarov** [comment]
@Tsvetoslav88 Тожа може да го затваряме май?

**Comment by Tsvetoslav88** [comment]
Вече да, току що го качих на тестовия OpenShift сървър. Ако искаш само си направи един pull на OpenShift Repository, за да си up-to-date

**Comment by petarov** [comment]
Оки, ще ги пулна нещата 👍
