### ISSUE TITLE
Изпращане на репорти в отделен background thread

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#51]
В момента имаме система за репроти, пакет - `net.vexelon.currencybg.srv.reports`, която главната нишка ползва, за да изпраща известия при грешки настъпили при теглене на валути от източниците. Репоритете обаче се пращат мигновено след края на поредния цикъл в главната нишка `Heartbeat.java`.  

Идята тук е, наместо да се пращат в края на цикъла на heartbeat-a, да се акумулират, например в базата от данни, и да се изпращат веднъж на конфигурируем интервал (примерно 30 мин. по подразбиране). Това може да стане чрез още 1 background нишка, която тегли текущите репорти от базата и ги праща.

Tasks:

  - [x] `reporter.type` - (telegram|sparkpost)
  - [x] Нова таблица за репортите - `Reports (id, createdon (DATE), message (TEXT))`
  - [x] Методи за работа с таблицата Reports в `MySQLDataSource.java`
  - [x] Промяна на `Heartbeat.java` да записва в базата -> в пакет `remote` -> `RemoteHeartbeat.java`
  - [x] Нова нишка - `ReporterHeartbeat.java` в пакет `reporter` и настройка в Bootstrap

Optional
 - [ ] Промяна `telegram.*` или `sparkpost.*`  -> `reporter.telegram.*` и `reporter.sparkpost.*`.

**Comment by Tsvetoslav88** [comment]
Дали колона source не трябва да е integer и да пишем кодовете(100,200..)

**Comment by petarov** [comment]
Добър въпрос. Май ще е по-добре така наистина. Ще обръщаме индексите в имена директно в бекенда.

Така или иначе данните са преходни, т.е., като ги изпратим трябва да изтрием SQL row-a за всички успешно изпратени съобщения, но с Integer-ите изглежда ще е по-пригледно.

**Comment by Tsvetoslav88** [comment]
Добре, ще го промяна да е Integer, ако решим после нещо  друго ще го сменим
