### ISSUE TITLE
Refactor properties for consistency 

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#58]
Трябва да се нанесат някой корекции в property-тата в `cbg.properties` файла. Следното не необходимо:

1. `timezone.server` => преименуване на `timezone`

Трябва да се добави и 1 ново property, съдържащо логическо име на конректния сървър:

2. `server.name` 

Трябва да се добави и 1 ново SparkPost property, съдържащо Subject:

3. `sparkpost.subject` - Добре е да конфигурираме subject-a  на мейла от настройките.

**Comment by Tsvetoslav88** [comment]
Трябва да се добави и 1 ново property, съдържащо логическо име на конректния сървър:
    server.name
Ще видя да го добавя това property, но какво име да му се сложи, както и къде трябва да се ползва?

**Comment by petarov** [comment]
server.name по дефаулт може да е празно. Това е просто арбитрарно наименование на сървъра. Може да е каквото и да е, пр., _oshft-server-01_.

Добре е да го има, тъй като може да го вкючваме в логовете или пък в репортите, които се пращат, за да идентифицираме кой сървър праща репорта.

**Comment by Tsvetoslav88** [comment]
Добре, ще го добавя във файла и ще го оставя празно. Също така ще видя да го добавя и в GlobalConfig.class,, когато ни трябва да може да го ползваме
