### ISSUE TITLE
Нов източник - ForexHouse

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#65]
[Списък на валути](http://forexhouse.eu/)

Няма дата и час на обновяване. Интервалът трябва да се уточни допълнително.

**Comment by Tsvetoslav88** [comment]
@petarov 
Гледам, че ForexHouse имат следните разделения на валутите:

- Основни

- Европа

- Азия

- Америка

- Африка

Предполагам, че ни ще използваме само "Основни"?

**Comment by petarov** [comment]
_Основните_ са добре за начало. Биткойна щеше също да е добре, но гледам че пише _по договаряне_, така че не ни върши работа засега.

**Comment by Tsvetoslav88** [comment]
@petarov Нещо имам проблем с парсването на данните. Въпреки, че подавам валиден обект, не ми връща данни за него
![default](https://user-images.githubusercontent.com/8929789/27254478-a658f754-5391-11e7-848f-7260d046e1e2.png)
Css-а, който ползват е доста "грозен"
`html.js_active.vc_desktop.vc_transform.vc_transform.vc_transform body#wp-spectrum.home.page.page-id-1767.page-template-default.csbody.body_header_normal.header-position-left.menu-appear-flyout.meny-right.header-v2.eagle1.wpb-js-composer.js-comp-ver-4.4.3.vc_responsive div#wrapper div#primary.content-area.no_breadcrumb_page div.container div.row div.content-wrap.col-xs-12.col-sm-12.col-md-12.col-lg-12 main#main.site-main article#post-1767.post-1767.page.type-page.status-publish.hentry div.entry-content div.section div.wpb_row.clearfix.vc_row-fluid.cs-row-fullwidth-wrap.vc_custom_1427193782202 div.no-container.cs-row-fullwidth.cshero_59454bd42b766 div.vc_col-sm-9.wpb_column.vc_column_container.vc_custom_1427197467722 div.wpb_wrapper div.wpb_tabs.wpb_content_element.style1 div.wpb_wrapper.wpb_tour_tabs_wrapper.ui-tabs.vc_clearfix.ui-widget.ui-widget-content.ui-corner-all div#tab-1427197476-1-96.wpb_tab.ui-tabs-panel.wpb_ui-tabs-hide.vc_clearfix.ui-widget-content.ui-corner-bottom div.wpb_text_column.wpb_content_element.wpb_animate_when_almost_visible.wpb_appear.wpb_start_animation div.wpb_wrapper div#tablepress-3_wrapper.dataTables_wrapper.no-footer table#tablepress-3.tablepress.tablepress-id-3.dataTable.no-footer`
като при всеки call сменят това `div.no-container.cs-row-fullwidth.cshero_59454bd42b766`

Нещо ми се изчерпаха идеите :)
Ако искаш мога да commit-на кода да направих и ти един опит?

**Comment by petarov** [comment]
Гледам, че всяка таблица си има `id` някакво. Пробвай с един такъв селектор дали няма да излезе нещо. 

`doc.select("#tablepress-3 > tbody")`

Иначе да, ако push-неш комитите, може да хвърля 1 око.

**Comment by Tsvetoslav88** [comment]
@petarov Дам, така стана, много странно, защото в css-а го дават `table#tablepress-3.tablepress.tablepress-id-3.dataTable.no-footer` и аз пробвах с пълното име, оправихме проблема.
На едно място са оставили space след десетичната точка, но това го оправих. Сега остава чуденката, за една валута няма курс купува и продава:
![default](https://user-images.githubusercontent.com/8929789/27262842-ab267b7c-5467-11e7-909c-b1e3b89121fc.png)
Как ще процедираме с нея?

**Comment by petarov** [comment]
Добър въпрос! Това ще доведе до error report-и при всички положения. Най-добре е валути без стойности купува/продава да бъдат директно пропускане. Няма смисъл да ги слагаме в базата на тоя етап.

**Comment by petarov** [comment]
Още нещо, тук има 2 валути в `Основни` и `Европа`, които пак ползват остарели кодове и трябва да се трансформират преди запис в базата:

  * `TRL` => трябва да е `TRY`
  * `BYR` => трябва да е `BYN`

**Comment by petarov** [comment]
Прав си, интервалът не го уточнихме. 4 часа като за начало е Ок. Ще видим в базата колко често настъпват промените.

**Comment by Tsvetoslav88** [comment]
@petarov Може ли пак 

> master-a ще го redeploy-неш ли на Staginga pls сега след merge-a :)

**Comment by Tsvetoslav88** [comment]
@petarov 
Деплойнах всичките неща на staging server, оставаме да чакаме и да видим какво правят от Crypto :)

**Comment by petarov** [comment]
👍 Супер! Нека видим какво ще излезе.
