### ISSUE TITLE
Нов източник - Changepartner

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#66]
[Списък на валути](http://www.changepartner.net/valuta.aspx)

Интервал на обновяване - всеки `4 часа`.

**Comment by Tsvetoslav88** [comment]
#87

**Comment by petarov** [comment]
@Tsvetoslav88  Тук се явява един проблем, който забелязах докато интегрирах източника в приложението. Оказва се, че следните валути са с остарели кодове:

1. Сръбски динар(**CSD**) -> кодът трябва да е **RSD**
1. Руска рубла(**RUR**) -> кодът трябва да е **RUB**
1. Турска лира(**TRL**)-> кодът трябва да е **TRY**

Ще можеш ли в кода на източника да ги напаснеш преди да бъдат записани в базата от данни? Така ще разрешим _проблема_ директно в сървъра. 😉

**Comment by Tsvetoslav88** [comment]
@petarov, да ще го видя да го оправя, предполагам е само за този изтучник?

**Comment by petarov** [comment]
Само при този е проблема, поне засега. Но сега като каза, може би решението може да се заложи директно в [normalizeCurrencyData метода.](https://github.com/vexelon-dot-net/currencybg.server/blob/master/src/main/java/net/vexelon/currencybg/srv/remote/AbstractSource.java#L121). Така ще е генерално за всички източници.
