### ISSUE TITLE
Грешен час при обновяване от Полана1 източник

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#69]
Има един кофти ефект тук. При източника Полана1, няма час на сайта и в момента кода взема датата вярно, но за час лепи часът на сървъра, а той е по `New York` време (production-a), а не `Europe/Sofia`. Оттам всички валути на Полана1 в базата са с коректна дата, но грешен час. 

Трябва да parse-нем само датата, а часът изришно да е текущия час (по време на parse-a на валутите), но по `Europe/Sofia` време.

**Comment by Tsvetoslav88** [comment]
Ако искаш мога да го взема аз това, ако имаш ти друга работа. Ще оставя Reporter-а засега?

**Comment by petarov** [comment]
Хвърли му 1 око, ако искаш. 👍  

Ще го мерджнем като patch за 1.1, че е належащо да го оправим в production-a.

**Comment by Tsvetoslav88** [comment]
Пепи, аз оправих този проблем, даже направих push, на нещата, но нещо Travis се сърди
net.vexelon.currencybg.srv.remote.Polana1SourceTests > test_Polana1_01 FAILED
    java.lang.AssertionError at Polana1SourceTests.java:32
, а при мен теста минава без проблем
