### ISSUE TITLE
Използване на Java Persistence API

### ISSUE THREAD

**Issue by Tsvetoslav88** [vexelon-dot-net/currencybg.server#73]
Мигриране от JDBC към JPA. Използване на Hibernate(Java persistence framework project)

**Comment by petarov** [comment]
Тук виждам следните точки на първо време:

1.  Коя версия на Hibernate е последната стабилна и ползвана и т.н.?
2. Сещам се, че имаше JDBC connection pooling библиотеки, дето се грижат за отварянето на връзките и кеширането им. Ние не ползваме в момента такава, но няма да е зле. Там само 1 име ми идва на ум - [c3po](https://github.com/swaldman/c3p0).  

С други думи, иска си малко research. 👨‍🔬

**Comment by petarov** [comment]
Махам само 1.3 milestone-a, докато дефинираме кога да го вкараме hibernate-a.
