### ISSUE TITLE
Тестове за UniCredit и SGExpress

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#83]
Ще ни трябват, подобно на другите източници, тестове за тези 2 източника. Просто да сме сигурни, че parse-a е ОК. ;)

@Tsvetoslav88  Ще погледнеш ли как можем да ги реализираме за тези 2-та? Тестовете трябва да parse-ват примерен sample (на другите източници са в [resources](https://github.com/vexelon-dot-net/currencybg.server/tree/master/src/test/resources) директорията в проекта) и да тестват на няколко произволно избрани валути, дали стойностите са ОК.

**Comment by Tsvetoslav88** [comment]
@petarov , да ще видя да направя тестовете и за тези 2-та източника, да имат тестове както другите.
