### ISSUE TITLE
Оптимизация на данните от cryptobg

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#88]
@Tsvetoslav88 

Докато гледах сайта на crypto.bg, видях че всъщност може направо да се ползва този адрес, за да преглеждаме последните BTC курсове. 

```
GET https://crypto.bg/tickers_header
```

```html
<table class='rates-hdr'>
<tr class='bitcoin'>
<td class='cur'>
BTC / lv.
</td>
<td class='left'>
<span class='trend-'><img src="/assets/trend__left-8563ddbc1ce716d12bfb811751c4d7fe.gif" alt="Trend  left" /></span> 4130.24
</td>
<td class='right'>4298.94</td><td class='arrow'> <span class='trend-'><img src="/assets/trend_-8563ddbc1ce716d12bfb811751c4d7fe.gif" alt="Trend " /></span></td>
</tr>
</table>
```
Няма нужа да дърпаме цялата страница. Това може и да реши проблемите с `java.io.IOException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0`, които се появяват начесто.

Ще трябва обаче да се пипнат и малко junit test-овете сигурно. 😉

**Comment by Tsvetoslav88** [comment]
@petarov Дам, изглежда по-добре. Ще видя да го направя тези дни :)

**Comment by Tsvetoslav88** [comment]
@petarov гледам, че си ми дал как да направя GET Request, само, че момента както са разписани интерфейсите и имплементациите, се връща винаги HttpResponse. Взимаме го като inputStream, гледам, че мога да го обърна към String:
`<table class='rates-hdr'>
<tr class='bitcoin'>
<td class='cur'>
BTC / лв.
</td>
<td class='left'>
<span class='trend-'><img src="/assets/trend__left-8563ddbc1ce716d12bfb811751c4d7fe.gif" alt="Trend  left" /></span> 4488.00
</td>
<td class='right'>4674.15</td><td class='arrow'> <span class='trend-'><img src="/assets/trend_-8563ddbc1ce716d12bfb811751c4d7fe.gif" alt="Trend " /></span></td>
</tr>
</table>`, но се чудя после как да го ползвам

**Comment by petarov** [comment]
После parse с jsoup както досега. Просто данните тук са по-директни.

**Comment by Tsvetoslav88** [comment]
Защото данните по-горе, не са html-ла от страницата, а са от GET Request
