### ISSUE TITLE
Unit тестове за източници в 1.4

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.server#95]
Нещо, което ще ни трябва, както винаги, са unit tests за новите източници:

1. Changeparnter
2. Forex House
3. Allianz

**Comment by Tsvetoslav88** [comment]
Дам, ще ги добавя, мерси!

**Comment by Tsvetoslav88** [comment]
@petarov На кой source трябваше да му видим проблема с валутите(не се парсваха както трябва)?

**Comment by petarov** [comment]
@Tsvetoslav88  Forex House беше. `BYR` и `CSD`.

**Comment by Tsvetoslav88** [comment]
@petarov 
Хубавата новина е, че са си оправили единия код:
![default](https://user-images.githubusercontent.com/8929789/28279925-bba35338-6b2a-11e7-8811-5272fe1d1317.png)
Лошата, че съм забравил 1,2 break в Case клаузата, което води до този проблем(stupid mistake). Оправил съм го ще го кача с unit тестовете :)

**Comment by petarov** [comment]
Добре. Лошо няма, щом проблемът е намерен :)
